# Generated by Django 2.2.2 on 2019-06-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('pic', models.ImageField(upload_to='static/uploads/startups')),
                ('contact', models.TextField(blank=True, max_length=13, null=True)),
                ('url', models.URLField(default='https://ecell.nitrr.ac.in')),
                ('founder', models.CharField(max_length=256)),
                ('address', models.TextField()),
                ('flag', models.BooleanField(default=False)),
                ('details', models.TextField(default='details coming soon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
