# Generated by Django 2.2.2 on 2019-07-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CA_Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(upload_to='uploads/caportal_screenshots/')),
                ('social_platform', models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('LI', 'LinkedIn'), ('WP', 'Whatsapp')], max_length=2)),
                ('status_flag', models.IntegerField(default=0)),
            ],
        ),
    ]
