# Generated by Django 2.2.2 on 2019-07-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca_requests',
            name='screenshot',
            field=models.ImageField(upload_to='uploads/caportal_screenshots/'),
        ),
    ]
