# Generated by Django 2.2.2 on 2019-07-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='applied',
            field=models.BooleanField(default=False),
        ),
    ]
