# Generated by Django 2.2.1 on 2019-06-04 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190602_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusAmbassadorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=128)),
                ('fb_score', models.PositiveIntegerField(default=0)),
                ('tw_score', models.PositiveIntegerField(default=0)),
                ('li_score', models.PositiveIntegerField(default=0)),
                ('wp_score', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='campus_ambassador_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CampusAmbassadurProfile',
        ),
    ]
