# Generated by Django 2.2.2 on 2020-04-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190830_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('GST', 'Guest'), ('VLT', 'Voluteer'), ('EXE', 'Executive'), ('MNG', 'Manager'), ('HCO', 'Head Co-ordinator'), ('OCO', 'Overall Co-ordinator'), ('CAB', 'Campus Ambassador'), ('STO', 'Startup Owner'), ('DRT', 'Director'), ('CDC', 'CDC Admin'), ('FAC', 'Faculty')], default='GST', max_length=3),
        ),
    ]
