# Generated by Django 2.2.2 on 2019-07-30 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190730_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ecell_user',
        ),
    ]
