# Generated by Django 2.2.2 on 2019-08-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190817_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='details_html',
            field=models.TextField(blank=True),
        ),
    ]
