# Generated by Django 2.2.2 on 2019-07-31 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_ecell_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventregister',
            old_name='profile',
            new_name='user',
        ),
    ]
