# Generated by Django 2.2.2 on 2019-07-31 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190731_0219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventregister',
            old_name='user',
            new_name='profile',
        ),
    ]
