# Generated by Django 2.2.2 on 2019-08-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_details_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inauguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('flag', models.BooleanField(default=False)),
                ('date', models.DateTimeField(blank=True)),
            ],
        ),
    ]
