# Generated by Django 2.2.2 on 2019-07-31 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190731_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventregister',
            old_name='profile',
            new_name='user',
        ),
    ]
