# Generated by Django 2.2.2 on 2019-07-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/uploads/team')),
                ('member_type', models.CharField(choices=[('DIR', 'Director, NIT Raipur'), ('HCD', 'Head of Career development'), ('FCT', 'Faculty Incharge'), ('MNG', 'Manager'), ('HCO', 'Head Co-ordinator'), ('OCO', 'Overall Co-ordinator'), ('EXC', 'Executive')], default='EXEC', max_length=3)),
                ('year', models.IntegerField(default=2018)),
            ],
        ),
    ]
