# Generated by Django 2.2.2 on 2019-07-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(null=True, upload_to='static/uploads/team'),
        ),
    ]
