# Generated by Django 2.2.2 on 2019-07-31 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_member_team_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='team_type',
        ),
    ]
