# Generated by Django 2.2.2 on 2019-07-31 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20190731_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='team_type',
            new_name='domain',
        ),
    ]
