# Generated by Django 2.2.2 on 2019-08-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='stipend',
            field=models.CharField(max_length=400),
        ),
    ]
