# Generated by Django 2.2.2 on 2020-04-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iportal', '0003_auto_20200415_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='beneficiaries',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='can_hire_interns',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='startup',
            name='describe_idea',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='end_product',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='file',
            field=models.FileField(blank=True, upload_to='static/uploads/iportal/more_details/'),
        ),
        migrations.AddField(
            model_name='startup',
            name='idea_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='startup',
            name='idea_in_a_nut_shell',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='startup',
            name='ideator_designation',
            field=models.TextField(choices=[('student', 'student'), ('faculty', 'faculty')], default='student', max_length=30),
        ),
        migrations.AddField(
            model_name='startup',
            name='innovation_in_this',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='mentor_designation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='startup',
            name='mentor_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
