# Generated by Django 2.2.2 on 2020-04-15 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iportal', '0005_job_brief'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='file',
        ),
        migrations.AlterField(
            model_name='startuplogo',
            name='logo',
            field=models.ImageField(blank=True, upload_to='static/uploads/iportal/logos/'),
        ),
        migrations.CreateModel(
            name='StartupPlanFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='static/uploads/iportal/startup_plan/')),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='iportal.Startup')),
            ],
        ),
    ]
