# Generated by Django 2.2.2 on 2020-04-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iportal', '0011_auto_20200430_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='idea_approved',
            field=models.CharField(choices=[('Approved', 'approved'), ('Rejected', 'rejected'), ('Pending', 'pending')], default='Pending', max_length=25),
        ),
    ]
