# Generated by Django 2.2.2 on 2020-05-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iportal', '0012_auto_20200430_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='idea_approved',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=25),
        ),
    ]
