# Generated by Django 2.2.2 on 2020-05-29 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iportal', '0012_jobapplication_college'),
        ('iportal', '0013_auto_20200501_0940'),
    ]

    operations = [
    ]
