# Generated by Django 2.2.2 on 2020-05-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iportal', '0014_merge_20200529_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='idea_approved',
            field=models.BooleanField(default=False),
        ),
    ]
