# Generated by Django 2.2.2 on 2019-07-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(null=True)),
                ('platform', models.CharField(choices=[['facebook', 'facebook'], ['whatsapp', 'whatsapp'], ['youtube', 'youtube'], ['instagram', 'instagram'], ['twitter', 'twitter']], max_length=100)),
                ('madeby', models.CharField(max_length=500)),
                ('url', models.URLField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
