# Generated by Django 2.2.2 on 2019-07-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default='asfasdf'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='url',
            field=models.URLField(blank=True, default='https://www.google.com/search?q=django+models+null+true&oq=django+models+null+true&aqs=chrome..69i57j0l5.5664j0j7&sourceid=chrome&ie=UTF-8'),
            preserve_default=False,
        ),
    ]
