# Generated by Django 2.2.2 on 2019-07-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caportal', '0004_auto_20190730_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittask',
            name='proof_pic',
            field=models.ImageField(upload_to='static/uploads/caportal/'),
        ),
    ]
