# Generated by Django 2.2.2 on 2019-07-31 19:43

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('caportal', '0005_auto_20190730_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittask',
            name='proof_pic',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=0, size=[700, 700], upload_to='static/uploads/caportal/'),
        ),
    ]
