# Generated by Django 2.2.2 on 2019-07-31 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caportal', '0006_auto_20190731_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittask',
            name='proof_pic',
            field=models.ImageField(upload_to='static/uploads/caportal/'),
        ),
    ]
