# Generated by Django 2.2.2 on 2019-08-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caportal', '0007_auto_20190731_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='platform',
            field=models.CharField(choices=[['facebook', 'facebook'], ['linkedin', 'linkedin'], ['whatsapp', 'whatsapp'], ['youtube', 'youtube'], ['instagram', 'instagram'], ['twitter', 'twitter']], max_length=100),
        ),
    ]
