# Generated by Django 2.2.2 on 2019-08-03 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caportal', '0008_auto_20190802_1307'),
        ('caportal', '0008_auto_20190803_0611'),
    ]

    operations = [
    ]
