# Generated by Django 2.2.2 on 2019-08-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(blank=True, max_length=256, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='static/uploads/startups')),
                ('contact', models.TextField(blank=True, max_length=13, null=True)),
                ('url', models.URLField(default='https://ecell.nitrr.ac.in')),
                ('founder', models.CharField(max_length=256)),
                ('address', models.TextField(blank=True, null=True)),
                ('flag', models.BooleanField(default=False)),
                ('details', models.TextField(default='details coming soon')),
                ('year', models.IntegerField(default=2019)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
