# Generated by Django 2.2.2 on 2019-08-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='static/uploads/sponsors')),
                ('contact', models.TextField(blank=True, max_length=13, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('spons_type', models.CharField(choices=[('ATS', 'Associate Sponsors'), ('PTS', 'Platinum Sponsors'), ('GDS', 'Gold Sponsors'), ('TLS', 'Title Sponsors'), ('PRS', 'Partner Sponsors')], default='AS', max_length=3)),
                ('flag', models.BooleanField(default=False)),
                ('year', models.IntegerField(default=2019)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
