# Generated by Django 2.2.2 on 2019-08-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0003_auto_20190823_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='importance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='spons_type',
            field=models.CharField(choices=[('ATS', 'Associate'), ('PLS', 'Platinum'), ('GDS', 'Gold'), ('TLS', 'Title'), ('PRS', 'Partner')], default='ATS', max_length=3),
        ),
    ]
