# Generated by Django 2.2.2 on 2019-07-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='app1', max_length=256)),
                ('log', models.CharField(max_length=256)),
                ('link', models.URLField(blank=True)),
                ('version', models.IntegerField(default=1)),
                ('flag', models.BooleanField(default=False)),
            ],
        ),
    ]
