# Generated by Django 2.2.2 on 2019-08-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='version',
            field=models.FloatField(default=1),
        ),
    ]
