# Generated by Django 2.2.2 on 2019-08-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_app', '0002_auto_20190828_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='version',
            field=models.CharField(default='1.0.0', max_length=10),
        ),
    ]
