# Generated by Django 2.2.2 on 2020-04-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_app', '0004_auto_20190828_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='version',
            field=models.IntegerField(),
        ),
    ]
